In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('titanic.tsv', sep = '\t', names = ['Serial_no', "Survived", "Pclass",
    "Name",
    "Sex",
    "Age",
    "SibSp",
    "Parch",
    "Ticket",
    "Fare",
    "Cabin",
    "Embarked"])

In [8]:
## How big is the data
df.shape

(891, 12)

In [10]:
## How does the data looks like
df.head()
df.sample(5) ## Give any 5

,Serial_no,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
347,348,1,3,"Davison, Mrs. Thomas Henry (Mary E Finck)",female,\N,1,0,386525,16.1000,\N,S
312,313,0,2,"Lahtinen, Mrs. William (Anna Sylfven)",female,26,1,1,250651,26.0000,\N,S
28,29,1,3,"O\'Dwyer, Miss. Ellen ""Nellie""",female,\N,0,0,330959,7.8792,\N,Q
618,619,1,2,"Becker, Miss. Marion Louise",female,4,2,1,230136,39.0000,F4,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.0708,\N,C

In [12]:
## What is the data type of the columns
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Serial_no  891 non-null    int64
 1   Survived   891 non-null    int64
 2   Pclass     891 non-null    int64
 3   Name       891 non-null    str
 4   Sex        891 non-null    str
 5   Age        891 non-null    str
 6   SibSp      891 non-null    int64
 7   Parch      891 non-null    int64
 8   Ticket     891 non-null    str
 9   Fare       891 non-null    float64
 10  Cabin      891 non-null    str
 11  Embarked   891 non-null    str
dtypes: float64(1), int64(5), str(6)
memory usage: 83.7 KB

In [13]:
## Are they missing any value
df.isnull().sum()

Serial_no    0
Survived     0
Pclass       0
Name         0
Sex          0
Age          0
SibSp        0
Parch        0
Ticket       0
Fare         0
Cabin        0
Embarked     0
dtype: int64

In [14]:
## How does the data locks mathemetically
df.describe()

        Serial_no    Survived      Pclass       SibSp       Parch        Fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean   446.000000    0.383838    2.308642    0.523008    0.381594   32.204208
std    257.353842    0.486592    0.836071    1.102743    0.806057   49.693429
min      1.000000    0.000000    1.000000    0.000000    0.000000    0.000000
25%    223.500000    0.000000    2.000000    0.000000    0.000000    7.910400
50%    446.000000    0.000000    3.000000    0.000000    0.000000   14.454200
75%    668.500000    1.000000    3.000000    1.000000    0.000000   31.000000
max    891.000000    1.000000    3.000000    8.000000    6.000000  512.329200

In [18]:
## Are there any duplicate rows
df.duplicated().sum()
#If there are any duplicate u can remove those using dropduplicate function

np.int64(0)

In [20]:
## Are there any correlation between columns
df.corr(numeric_only = True)

           Serial_no  Survived    Pclass     SibSp     Parch      Fare
Serial_no   1.000000 -0.005007 -0.035144 -0.057527 -0.001652  0.012658
Survived   -0.005007  1.000000 -0.338481 -0.035322  0.081629  0.257307
Pclass     -0.035144 -0.338481  1.000000  0.083081  0.018443 -0.549500
SibSp      -0.057527 -0.035322  0.083081  1.000000  0.414838  0.159651
Parch      -0.001652  0.081629  0.018443  0.414838  1.000000  0.216225
Fare        0.012658  0.257307 -0.549500  0.159651  0.216225  1.000000

In [21]:
df.corr(numeric_only = True)['Survived']

Serial_no   -0.005007
Survived     1.000000
Pclass      -0.338481
SibSp       -0.035322
Parch        0.081629
Fare         0.257307
Name: Survived, dtype: float64